spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cashflow
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  liquibase:
    change-log: /db/changelogs/changelog-master.xml

server:
  port: 8080
