spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cashflow
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.xml
    default-schema: public
  application:
    name: Cashflow

server:
  port: 8080
